name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'

    - name: Build and Test
      run: dotnet build --configuration Release
        
    - name: Run SonarQube Analysis
      run: dotnet sonarscanner begin /k:"your-project-key" /d:sonar.login=${{ secrets.SONARQUBE_TOKEN }}
    
    - name: Build and Test (again)
      run: dotnet build --configuration Release

    - name: Run SonarQube Analysis (end)
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONARQUBE_TOKEN }}
